#ifndef TALLER_H_INCLUDED
#define TALLER_H_INCLUDED

// def tipos de datos
typedef enum {PASTAS, PASTELERIA, MILANESAS, PIZZAS, ENSALADAS, CHIVITOS, HAMBURGUESAS, COCTELERIA} nomTaller;

#endif // TALLER_H_INCLUDED
